name: PR Title Validation

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"

          # Allow Dependabot PRs to pass through (they're automated)
          if [[ "$PR_AUTHOR" == "dependabot[bot]" ]]; then
            echo "✅ Dependabot PR detected - allowing automated dependency updates"
            exit 0
          fi

          # Block PRs with Dependabot-style naming patterns from human contributors
          if [[ "$PR_TITLE" =~ ^(chore|ci)\(deps\): ]]; then
            echo "❌ PR title follows Dependabot naming pattern: $PR_TITLE"
            echo "This naming pattern is reserved for automated dependency updates."
            echo "Please use a more descriptive title for your changes."
            exit 1
          fi

          # Require conventional commit format for human PRs
          if [[ ! "$PR_TITLE" =~ ^(feat|fix|chore|docs|style|refactor|perf|test|ci|build|revert):\ .+ ]]; then
            echo "❌ PR title does not follow conventional commit format: $PR_TITLE"
            echo "Expected format: type(scope): description"
            echo "Examples:"
            echo "  feat: add user authentication"
            echo "  fix: resolve login bug"
            echo "  docs: update README"
            echo "  chore: update dependencies"
            exit 1
          fi

          echo "✅ PR title validation passed: $PR_TITLE"
