name: PR Title Validation

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Validate PR Title
        uses: actions/github-script@v8
        with:
          script: |
            const prTitle = context.payload.pull_request.title;
            const prAuthor = context.payload.pull_request.user.login;

            // Allow Dependabot PRs to pass through (they're automated)
            if (prAuthor === 'dependabot[bot]') {
              console.log('✅ Dependabot PR detected - allowing automated dependency updates');
              return;
            }

            // Block PRs with Dependabot-style naming patterns from human contributors
            if (prTitle.match(/^(chore|ci)\(deps\):/)) {
              const message = `❌ PR title follows Dependabot naming pattern: ${prTitle}\nThis naming pattern is reserved for automated dependency updates.\nPlease use a more descriptive title for your changes.`;
              core.setFailed(message);
              return;
            }

            // Require conventional commit format for human PRs
            const conventionalCommitPattern = /^(feat|fix|chore|docs|style|refactor|perf|test|ci|build|revert):\s.+$/;
            if (!conventionalCommitPattern.test(prTitle)) {
              const message = `❌ PR title does not follow conventional commit format: ${prTitle}\nExpected format: type(scope): description\nExamples:\n  feat: add user authentication\n  fix: resolve login bug\n  docs: update README\n  chore: update dependencies`;
              core.setFailed(message);
              return;
            }

            console.log(`✅ PR title validation passed: ${prTitle}`);
