name: Update Robots.txt

on:
  push:
    branches: [main, testing]
    paths-ignore:
      - "robots.txt"

# Ensure only one workflow runs at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-robots:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update robots.txt
        run: |
          MAIN_ROBOTS=$(printf "%s\\n" \
            "User-agent: *" \
            "Allow: /" \
            "" \
            "# Legal Pages - Specify exact paths" \
            "Allow: /privacy$" \
            "Allow: /tos$" \
            "" \
            "# Disallow incorrect legal page paths" \
            "Disallow: /item/*/privacy" \
            "Disallow: /item/*/tos" \
            "Disallow: /*/privacy" \
            "Disallow: /*/tos" \
            "" \
            "# Main Value Pages" \
            "Allow: /values" \
            "Allow: /values/calculator" \
            "Allow: /item/*/" \
            "Allow: /item/*/*" \
            "" \
            "# Important Trading Sections" \
            "Allow: /trading" \
            "Allow: /values?sort=*" \
            "Allow: /values/calculator" \
            "" \
            "# Static Resources" \
            "Allow: /*.css$" \
            "Allow: /*.js$" \
            "Allow: /*.webp$" \
            "" \
            "# Clean URLs" \
            "Disallow: /*?page=" \
            "Disallow: /*?filter=" \
            "Disallow: /api/" \
            "" \
            "# Disallow recommended Cloudflare endpoints" \
            "Disallow: /cdn-cgi/" \
            "" \
            "Sitemap: https://jailbreakchangelogs.xyz/sitemap.xml")

          if [[ $GITHUB_REF == "refs/heads/main" ]]; then
            echo "$MAIN_ROBOTS" > robots.txt
          else
            printf "%s\\n" \
              "User-agent: *" \
              "Disallow: /" > robots.txt
          fi

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet robots.txt; then
            echo "No changes to robots.txt"
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in robots.txt"
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes
        if: steps.changes.outputs.changes == 'true'
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add robots.txt
          if ! git commit -m "Update robots.txt based on branch [skip ci]"; then
            echo "No changes to commit"
            exit 0
          fi
          git push || {
            echo "Failed to push changes"
            exit 1
          }
